name: Android IRIS integrate - Post-merge

run-name: Android IRIS integrate post-merge CI deploy ${{ github.ref_name }}

# Run on push to master.
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/android-iris-integrate-*
      - android/iris-scan/integrate/**


concurrency:
  # We want to share a group name across one branch, where only one pipeline can run at a time.
  group: android-iris-integrate-postmerge-pipeline-${{ github.ref_name }}
  cancel-in-progress: false

env:
  ANDROID_HOME: /Users/sighticdev01/Library/Android/sdk

defaults:
  run:
    working-directory: android/iris-scan/integrate

jobs:
  build-and-deploy-android-iris-integrate-ci:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Create local.properties
        working-directory: android/iris-scan
        run: |
          touch local.properties

      - name: Publish release to iris-integrate-android-dev
        run: |
          eval "$(rbenv init -)"
          echo -n ${{ secrets.TOKEN_GITHUB_CLI }} > .githubtoken.txt
          ruby io.rb publish