name: Release with ruby

run-name: Android IRIS integrate CI deploy ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.A_TOKEN }}"

      - name: Publish release
        working-directory: ./app
        run: |
          echo -n ${{ secrets.A_TOKEN }} > .githubtoken.txt
          ruby io.rb publish