# This is a basic workflow to help you get started with Actions

name: PublishToMavenCentral

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: env
      - run: echo "${{ vars.ASECRETVARIABLE }}"
      - run: echo "${{ github.ref_name }}"

      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Get library version
        run: echo "VERSION_NAME=$( ./gradlew -q app:getLibraryVersion )" >> $GITHUB_ENV
      - run: echo "${{ env.VERSION_NAME }}"

      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Check Hash
        run: echo "${{ env.hash }}"
    
     
  
