name: Release with ruby

run-name: Android IRIS integrate CI deploy ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Publish release
        working-directory: ./app
        run: |
          echo -n ${{ secrets.A_TOKEN }} > .githubtoken.txt
          ruby random.rb publish