# This is a basic workflow to help you get started with Actions

name: PublishToMavenCentral

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: env
      - run: echo "${{ vars.ASECRETVARIABLE }}"
      - run: echo "${{ github }}"
    
     
  
