name: Release with ruby

run-name: Android IRIS integrate CI deploy ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish release
        working-directory: ./app
        env:
          TOKEN: ${{ secrets.A_TOKEN }}
        run: |
          echo -n "$TOKEN" > .githubtoken.txt
          ruby io.rb publish