name: Publish Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build artifact
        run: ./gradlew assemble

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./app/build/outputs/aar/app-release.aar

      - name: Get library version
        run: echo "VERSION_NAME=$( ./gradlew -q app:getLibraryVersion )" >> $GITHUB_ENV
      - run: echo "${{ env.VERSION_NAME }}"
      - run: echo "${{ secrets.GITHUB_TOKEN }}"

      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION_NAME }}
        run: |
          "gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag-git$git_hash" \" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.create_release.outputs }}"