name: Traverse paths

run-name: Something

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
         ruby-version: '3.2.2'
         bundler-cache: true
      - run: bundle exec rake

      - name: Publish release
        working-directory: ./app
        run: |
          echo -n ${{ secrets.A_TOKEN }} > .githubtoken.txt
          ruby random.rb something