name: Traverse paths

run-name: Something

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "$HOME"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Publish release
        working-directory: ./app
        run: |
         echo -n ${{ secrets.A_TOKEN }} > .githubtoken.txt
         ruby random.rb something